### ISSUE TITLE
CKB System Scripts Automation and Security Requirements Epic

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb-system-scripts#17]
This is an Epic, please start new issue for each objective listed below.

### Reproducible Docker Builder

- [x] Provide a Dockerfile to show how we create the builder.

Security Requirements:

- [x] The Dockerfile must verify the downloaded gcc package checksum.

### Build using an existing Docker Builder image

- [x] Ease building the scripts using a docker image.

Security Requirements:

- [x] The build script must verify the checksum of the builder image

CI has already been setup in #15 

### Binary Build and Crate Publish via CI

- [x] Do not store the binaries in the repository. Developer and CI must build the scripts into binaries by themselves.

Setup CI to automate the publishing workflow:

- Build binaries
- Run test
- Publish the Rust crate including the binaries.

Security Requirements:

- [x] Publish the code hashes of each system scripts in the release.

**Comment by xxuejie** [comment]
The docker files are kept here: https://github.com/nervosnetwork/ckb-riscv-gnu-toolchain/tree/master/docker

And it actually uses a slightly different way: instead of downloading official gcc distribution, we are using the [riscv gcc fork](https://github.com/riscv/riscv-gnu-toolchain), which packs all the GNU toolchain in an easier way to build. For reproducible build, the docker files have some [extra steps](https://github.com/nervosnetwork/ckb-riscv-gnu-toolchain/blob/master/docker/bionic.dockerfile#L12-L13):

1. It ensures local repository does not have dirty changes.
2. It keeps a `REVISION` file containing the original commit from which gcc is built

This way IMO also ensures the built toolchain can be verified. Any thoughts @doitian ?
